import { readFileSync, writeFileSync } from "node:fs";
import type { ContentBundle } from "@hd2d/content";
import { canonicalContentJson, fnv1a32 } from "@hd2d/sim";

/** fnv1a32(canonicalContentJson(bundle)) as 8 lowercase hex chars (interfaces section 6). */
export function computeContentVersion(bundle: ContentBundle): string {
  return fnv1a32(canonicalContentJson(bundle)).toString(16).padStart(8, "0");
}

export const VERSION_FILE = new URL(
  "../../../packages/content/src/data/content-version.generated.ts",
  import.meta.url,
);

export function renderVersionFile(version: string): string {
  return `// GENERATED by tools/content (pnpm --filter @hd2d/content-tools build-version). Do not edit by hand.
export const CONTENT_VERSION: string = "${version}";
`;
}

export function readWrittenVersion(): string | null {
  const m = /CONTENT_VERSION: string = "([0-9a-f]{8})"/.exec(readFileSync(VERSION_FILE, "utf8"));
  return m?.[1] ?? null;
}

export function writeVersionFile(version: string): void {
  writeFileSync(VERSION_FILE, renderVersionFile(version));
}
