// Generates src/tables.generated.ts from BALANCE. NOT sim runtime, so it may use Math.pow and floats
// (docs/interfaces.md §1.2, §7). Run: node packages/sim/scripts/gen-tables.ts
// A unit test regenerates every table in memory and diffs it against the file (node-tests/tables.test.ts).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { BALANCE as B } from "../src/balance.ts";

export const PACE_MIN = B.PACE_MIN;
export const PACE_MAX = B.PACE_MAX;
const BP = 10_000;

/** (PACE_REF/Pace)^PACE_EXP clamped to PACE_CLAMP, in basis points, for integer pace 15..120 (index = pace - 15). */
export function computePaceFactorBp(): number[] {
  const out: number[] = [];
  for (let pace = PACE_MIN; pace <= PACE_MAX; pace++) {
    const f = Math.min(
      B.PACE_CLAMP[1],
      Math.max(B.PACE_CLAMP[0], (B.PACE_REF / pace) ** B.PACE_EXP),
    );
    out.push(Math.round(f * BP));
  }
  return out;
}

/** TIER_GROWTH^(tier-1) in basis points, tier 1..10 (index = tier - 1). py item_score. */
export function computeTierGrowthBp(): number[] {
  return Array.from({ length: 10 }, (_, i) => Math.round(B.TIER_GROWTH ** i * BP));
}

const tierPriceF = (tier: number): number => B.PRICE_T1 * B.PRICE_GROWTH ** (tier - 1);

/** PRICE_T1 x PRICE_GROWTH^(tier-1), whole gold, tier 1..10. py tier_price. */
export function computeTierPrice(): number[] {
  return Array.from({ length: 10 }, (_, i) => Math.round(tierPriceF(i + 1)));
}

/** UPG_COST[tier-1][u]: tier_price x UPG_COST_BASE x UPG_COST_GROWTH^u, whole gold, u = 0..14. py upg_cost. */
export function computeUpgCost(): number[][] {
  return Array.from({ length: 10 }, (_, t) =>
    Array.from({ length: 15 }, (_, u) =>
      Math.round(tierPriceF(t + 1) * B.UPG_COST_BASE * B.UPG_COST_GROWTH ** u),
    ),
  );
}

const goldUnitF = (c: number): number => B.GOLD_L1 * B.GOLD_GROWTH_CH ** (c - 1);

/** GOLD_L1 x GOLD_GROWTH_CH^(chapter-1), whole gold, chapter 1..30 (index = chapter - 1). py gold_unit. */
export function computeGoldUnit(): number[] {
  return Array.from({ length: B.CHAPTERS }, (_, i) => Math.round(goldUnitF(i + 1)));
}

/** LEVEL_GOLD[chapter-1][index-1], whole gold. py level_gold (boss = index 10 pays BOSS_GOLD_MULT). */
export function computeLevelGold(): number[][] {
  return Array.from({ length: B.CHAPTERS }, (_, c) =>
    Array.from({ length: B.LEVELS_PER_CH }, (_, p) => {
      const g = goldUnitF(c + 1) * (1 + B.GOLD_IN_CH_STEP * p);
      return Math.round(p === B.LEVELS_PER_CH - 1 ? g * B.BOSS_GOLD_MULT : g);
    }),
  );
}

const rows1 = (name: string, doc: string, t: readonly number[], per = 10): string => {
  const rows: string[] = [];
  for (let i = 0; i < t.length; i += per) rows.push(`  ${t.slice(i, i + per).join(", ")},`);
  return `/** ${doc} */\nexport const ${name}: readonly number[] = [\n${rows.join("\n")}\n];\n`;
};
const rows2 = (name: string, doc: string, t: readonly (readonly number[])[]): string => {
  const rows = t.map((r) => `  [${r.join(", ")}],`);
  return `/** ${doc} */\nexport const ${name}: readonly (readonly number[])[] = [\n${rows.join("\n")}\n];\n`;
};

export function renderTables(): string {
  return `// GENERATED by packages/sim/scripts/gen-tables.ts from BALANCE. Do not edit; a unit test diffs a fresh generation.
${rows1("PACE_FACTOR_BP", "PACE_FACTOR_BP[pace - 15], pace = 15..120: (35/pace)^0.7 clamped to 0.6..1.8, in basis points.", computePaceFactorBp())}
${rows1("TIER_GROWTH_BP", "TIER_GROWTH_BP[tier - 1], tier 1..10: 1.40^(tier-1) in basis points (economy_sim item_score).", computeTierGrowthBp())}
${rows1("TIER_PRICE", "TIER_PRICE[tier - 1], tier 1..10: 1150 x 1.405^(tier-1), whole gold (economy_sim tier_price).", computeTierPrice())}
${rows2("UPG_COST", "UPG_COST[tier - 1][u], u = 0..14: tier price x 0.25 x 1.3^u, whole gold (economy_sim upg_cost).", computeUpgCost())}
${rows1("GOLD_UNIT", "GOLD_UNIT[chapter - 1], chapter 1..30: 100 x 1.125^(chapter-1), whole gold (economy_sim gold_unit).", computeGoldUnit())}
${rows2("LEVEL_GOLD", "LEVEL_GOLD[chapter - 1][index - 1], index 1..10: first-clear gold, boss = index 10 (economy_sim level_gold).", computeLevelGold())}`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const dest = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "../src/tables.generated.ts",
  );
  fs.writeFileSync(dest, renderTables());
  console.log(`wrote ${dest}`);
}
