// Generates src/tables.generated.ts. NOT sim runtime, so it may use Math.pow (docs/interfaces.md §1.2).
// Run: node packages/sim/scripts/gen-tables.ts   (a unit test regenerates the table in memory and diffs it)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const PACE_MIN = 15;
export const PACE_MAX = 120;

/** (35/Pace)^0.7 clamped to 0.6..1.8, in basis points, for integer pace 15..120 (index = pace - 15). */
export function computePaceFactorBp(): number[] {
  const out: number[] = [];
  for (let pace = PACE_MIN; pace <= PACE_MAX; pace++) {
    const f = Math.min(1.8, Math.max(0.6, (35 / pace) ** 0.7));
    out.push(Math.round(f * 10_000));
  }
  return out;
}

export function renderTables(): string {
  const rows: string[] = [];
  const t = computePaceFactorBp();
  for (let i = 0; i < t.length; i += 10) rows.push(`  ${t.slice(i, i + 10).join(", ")},`);
  return `// GENERATED by packages/sim/scripts/gen-tables.ts. Do not edit; a unit test diffs a fresh generation.
/** PACE_FACTOR_BP[pace - 15], pace = 15..120: (35/pace)^0.7 clamped to 0.6..1.8, in basis points. */
export const PACE_FACTOR_BP: readonly number[] = [
${rows.join("\n")}
];
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const dest = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "../src/tables.generated.ts",
  );
  fs.writeFileSync(dest, renderTables());
  console.log(`wrote ${dest}`);
}
