import { z } from "zod";

/** Every char content may contain and the sim accepts as a key (single source of truth). */
export const TYPABLE_CHARS =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,'-?!;:\"()";
const escapeForCharClass = (s: string): string => s.replace(/[\\\]^-]/g, "\\$&");
export const TypableText = z
  .string()
  .regex(new RegExp(`^[${escapeForCharClass(TYPABLE_CHARS)}]+$`));

export const Biome = z.enum(["forest", "ruins", "cave", "hollow", "hushwood", "fen", "grove"]); // v2.0: + Ch2 (grove = the boss arena, like hollow)
export type Biome = z.infer<typeof Biome>;
export const WordTier = z.number().int().min(1).max(10);
export const DamageType = z.enum(["slash", "pierce", "blunt", "arcane", "fire", "ice", "light"]);
export type DamageType = z.infer<typeof DamageType>;
export const Rarity = z.enum(["C", "U", "R", "E", "L"]);
export type Rarity = z.infer<typeof Rarity>;
export const GearSlot = z.enum(["weapon", "armor", "charm"]);
export type GearSlot = z.infer<typeof GearSlot>;
export const WeaponArchetype = z.enum(["sword", "dagger", "staff", "hammer"]);
export type WeaponArchetype = z.infer<typeof WeaponArchetype>;

export const WordEntry = z.object({
  text: TypableText.max(120),
  key: z.string().min(1), // SRS/journal key; = text.toLowerCase() for single words
  kind: z.enum(["word", "collocation", "sentence"]),
  tier: WordTier,
  freqRank: z.number().int().positive().optional(),
  cefr: z.enum(["A1", "A2", "B1", "B2", "C1", "C2"]).optional(),
  biomes: z.array(Biome).default([]),
  uses: z
    .array(
      z.enum([
        "plate",
        "guard",
        "doom",
        "finisher",
        "secondWind",
        "minigame",
        "trial",
        "riddle",
        "intro",
      ]),
    ) // v2.0: + riddle, intro
    .min(1),
  definition: z.string().min(1).max(140), // simple English
  example: z.string().min(1).max(160),
  translations: z.record(z.string(), z.string()).default({}), // BCP-47 tag -> text (optional, Journal only)
  /**
   * v2.0 "introduced in chapter N" (absent = 1). Sentence pools (doom, finisher, secondWind, minigame, intro) take
   * entries with (chapter ?? 1) === level.chapter; every other pool (current, review, biome, weak, guard, riddle) takes
   * (chapter ?? 1) <= level.chapter. So nothing authored for Ch2 can reach a Ch1 level.
   */
  chapter: z.number().int().min(1).max(30).optional(),
  /** v2.0 riddle text (simple English, must not contain the answer). Absent = `definition` is the clue. */
  clue: z.string().min(1).max(90).optional(),
});
export type WordEntry = z.infer<typeof WordEntry>;

export const Gimmick = z.enum(["fading", "scrambled"]);
export type Gimmick = z.infer<typeof Gimmick>;
/** v2.0 healer (§3.5). Numbers at pace 35 / standard preset; the sim pace-scales the cadence. */
export const HealDef = z.object({
  everyS: z.number().positive(), // Moth Mender: 10
  frac: z.number().positive().max(1), // of each target's max HP; Moth Mender: 0.15
  maxTargets: z.number().int().min(1).max(4).default(4),
  maxHeals: z.number().int().min(0).default(0), // per encounter; 0 = unlimited
});
export const EnemyDef = z.object({
  id: z.string(),
  name: z.string(),
  archetype: z.enum(["grunt", "brute", "speedster", "boss"]),
  spriteId: z.string(),
  scale: z.number().positive().default(1),
  flying: z.boolean().default(false),
  baseIntervalS: z.number().positive(), // grunt 9, brute 12, speedster 5 (scaled by pace factor)
  heavy: z.boolean().default(false),
  plateLength: z.tuple([z.number().int().min(2), z.number().int().max(14)]),
  weaknesses: z.array(DamageType).min(1),
  shield: z.number().int().min(1).max(9),
  hpWeight: z.number().positive().default(1), // share of the wave's HP pool
  hitWeight: z.number().positive().default(1), // x encounter gruntHit
  heal: HealDef.optional(), // v2.0: healer capability (archetype stays grunt/brute/...)
});
export type EnemyDef = z.infer<typeof EnemyDef>;

export const EnemyRef = z
  .object({
    enemy: z.string(),
    gimmick: Gimmick.optional(),
    attackPower: z.number().positive().optional(), // v2.0: per-ref P (x chapter par armor); overrides the encounter / adds P
    elite: z.boolean().optional(), // v2.0: elite tag (presentation); requires attackPower
  })
  .refine(
    (r) => r.elite !== true || r.attackPower !== undefined,
    "an elite ref must set attackPower",
  );
export type EnemyRef = z.infer<typeof EnemyRef>;
export const EncounterDef = z
  .object({
    name: z.string(),
    hp: z.number().positive(), // HP pool per wave (generated by tools/balance, D32)
    gruntHit: z.number().positive(),
    /** v1.9 guard leak: Attack Power P of this encounter's enemies, x the chapter par armor score. 1 = no leak at par gear. */
    attackPower: z.number().positive().default(1),
    waves: z.array(z.array(EnemyRef).min(1).max(4)).min(1), // >1 wave -> WaveStarted
  })
  .refine(
    (e) => new Set(e.waves.flat().flatMap((r) => (r.gimmick ? [r.gimmick] : []))).size <= 2,
    "max 2 gimmicks/encounter",
  );
export type EncounterDef = z.infer<typeof EncounterDef>;

export const FallingRubbleDef = z.object({
  kind: z.literal("fallingRubble"),
  lanes: z.number().int().min(2).max(4),
  spawnEveryS: z.number().positive(),
  fallS: z.number().positive(),
  clearAtkMult: z.number().positive(),
  missHit: z.number().positive(),
});
/** v2.0 Riddle of Leaves (§3.6). Timer at pace 35 = readS + answerS, x the boss-script pace factor. */
export const RiddleDef = z.object({
  kind: z.literal("riddle"),
  count: z.number().int().min(1).max(9).default(5),
  leaves: z.literal(3).default(3),
  readS: z.number().positive(),
  answerS: z.number().positive(),
  gapS: z.number().positive().default(1.5),
  clearAtkMult: z.number().positive(),
  missHit: z.number().positive(),
  lengthRange: z.tuple([z.number().int().min(2), z.number().int().max(14)]).default([3, 8]),
});
/** v2.0: a discriminated union (was the falling-rubble object; Ch1 data parses unchanged). */
export const MinigameDef = z.discriminatedUnion("kind", [FallingRubbleDef, RiddleDef]);
export type MinigameDef = z.infer<typeof MinigameDef>;
export const BossDef = z.object({
  id: z.string(),
  name: z.string(),
  title: z.string(),
  enemyId: z.string(),
  hp: z.number().positive(),
  hit: z.number().positive(),
  /** v1.9 guard leak: the boss's Attack Power P, x the chapter par armor score. */
  attackPower: z.number().positive().default(1),
  plateLength: z.tuple([z.number().int(), z.number().int()]),
  phase1: z.object({
    endAtHpPct: z.number().default(66),
    adds: z.array(EnemyRef).max(2),
    /** v1.9 guard leak: Attack Power P of the phase-1 adds, x par armor. */
    addsAttackPower: z.number().positive().default(1),
  }),
  phase2: z.object({
    endAtHpPct: z.number().default(33),
    doomEveryS: z.number().positive(),
    minDoomSpells: z.number().int().min(1),
  }),
  phase3: z.object({ minigame: MinigameDef, finisherText: TypableText }),
  breatherS: z.number().default(2),
  introS: z.number().default(4),
});
export type BossDef = z.infer<typeof BossDef>;

export const StarChallenge = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("untouched"), maxHits: z.number().int().min(0) }),
  z.object({ kind: z.literal("parTime"), slack: z.number().default(1.15) }), // par = parRefS * 35/pace * slack
  z.object({ kind: z.literal("streak"), combo: z.number().int().positive() }),
  z.object({ kind: z.literal("guardian"), parries: z.number().int().positive() }),
  z.object({ kind: z.literal("noSkills") }),
]);
export type StarChallenge = z.infer<typeof StarChallenge>;
export const Segment = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("walk"), seconds: z.number().positive(), heal: z.boolean() }),
  z.object({ kind: z.literal("encounter"), encounter: EncounterDef }),
  z.object({ kind: z.literal("boss"), bossId: z.string() }),
]);
export type Segment = z.infer<typeof Segment>;
export const LevelDef = z.object({
  id: z.string().regex(/^ch\d+-l\d+$/),
  chapter: z.number().int().min(1).max(30),
  index: z.number().int().min(1).max(10),
  name: z.string(),
  biome: Biome,
  layoutId: z.string(), // LDtk/Tiled level id (T2.2)
  kind: z.enum(["normal", "boss"]),
  wordTier: WordTier,
  tierMix: z
    .object({ current: z.number(), review: z.number(), biome: z.number(), weak: z.number() })
    .refine((m) => m.current + m.review + m.biome + m.weak === 100)
    .default({ current: 60, review: 20, biome: 15, weak: 5 }),
  plateLength: z.tuple([z.number().int(), z.number().int()]),
  segments: z.array(Segment).min(2),
  star3: StarChallenge,
  parRefS: z.number().positive(), // active time of the 35-WPM reference typist
  tutorial: z.boolean().default(false),
  /**
   * v2.0: when present, the `review` pool = plate words (kind "word") whose biomes intersect this list, any tier
   * (Ch2: ["forest", "ruins", "cave"] = the Ch1 biome words). Absent = the v1 rule (tier < wordTier, no biome).
   */
  reviewBiomes: z.array(Biome).min(1).optional(),
});
export type LevelDef = z.infer<typeof LevelDef>;

export const GearDef = z
  .object({
    id: z.string(),
    slot: GearSlot,
    archetype: WeaponArchetype.optional(), // required iff slot === "weapon"
    tier: z.number().int().min(1).max(10),
    name: z.string(),
    spriteId: z.string(),
    flavor: z.string().optional(),
    // Stats are derived (BALANCE): score = TIER_GROWTH^(tier-1) * RARITY_MULT[rarity] * (1 + UPG_STEP*upgrade).
    // weapon -> ATK, armor -> HP, charm -> sqrt into both. Rarity/upgrade are per instance (save GearInstance).
  })
  .refine((g) => (g.slot === "weapon") === (g.archetype !== undefined));
export type GearDef = z.infer<typeof GearDef>;

export const ActiveSkillDef = z.object({
  id: z.enum([
    "slashWave",
    "piercingThrust",
    "fireball",
    "frostLock",
    "mendingLight",
    "aegis",
    "reveal",
  ]),
  name: z.string(),
  description: z.string(), // may use {dmg},{charge},{secs} placeholders filled from BALANCE
  iconId: z.string(),
  vfxId: z.string(),
  sfxId: z.string(),
  unlockLevel: z.string().optional(),
});
export type ActiveSkillDef = z.infer<typeof ActiveSkillDef>;
export const PassiveDef = z.object({
  id: z.enum([
    "cleanCut",
    "bulwarkStreak",
    "steadyHands",
    "riposte",
    "ironWill",
    "openingGambit",
    "lastStand",
    "comeback",
    "calmMind",
  ]),
  name: z.string(),
  description: z.string(),
  tag: z.enum(["precision", "speed", "defense", "tech", "economy"]),
  iconId: z.string(),
  unlockLevel: z.string().optional(),
});
export type PassiveDef = z.infer<typeof PassiveDef>;
export const TrialDef = z.object({
  id: z.string(),
  name: z.string(),
  durationS: z.literal(60),
  // Standardized pool (same for everyone); the run seed picks one. >= 1600 chars covers 60 s at 300+ WPM.
  passages: z.array(TypableText.min(1600)).min(30),
});

export type TrialDef = z.infer<typeof TrialDef>;

export const ContentBundle = z.strictObject({
  words: z.array(WordEntry),
  enemies: z.array(EnemyDef),
  bosses: z.array(BossDef),
  levels: z.array(LevelDef),
  gear: z.array(GearDef),
  actives: z.array(ActiveSkillDef),
  passives: z.array(PassiveDef),
  trials: z.array(TrialDef),
});
export type ContentBundle = z.infer<typeof ContentBundle>;
/** fnv1a32(canonicalContentJson(bundle)) as 8 hex chars; emitted by tools/content at build time. */
export const CONTENT_VERSION: string = "00000000"; // PLACEHOLDER: tools/content overwrites this at build time (the doc has `declare const`)
